apiVersion: apps/v1
kind: Deployment
metadata:
  name: oee-deployment
  labels:
    app: oee
  annotations:
    ingress.kubernetes.io/proxy-body-size: '5m'
    nginx.org/client-max-body-size: '5m'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oee
  template:
    metadata:
      labels:
        app: oee
    spec:
      containers:
        - name: oee
          image: 10.32.0.105:5000/oee:1.0.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '512Mi'
              cpu: '50m'
            limits:
              memory: '512Mi'
              cpu: '1000m'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: oee-service
spec:
  selector:
    app: oee
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
